# These are supported funding model platforms

github: [SRInternet, Welsonpeaches, RBC-AE3803]
buy_me_a_coffee: https://afdian.com/a/srinternet
custom: ['www.bilibili.com/h5/upower/index?mid=1969160969&navhide=1&share=1', 'afdian.com/a/srinternet']
